sudo: required
services:
  - docker

before_install:
  - docker build -t twsbank/docker-react -f Dockerfile.dev .

script:
  - docker run twsbank/docker-react npm run test -- --coverage --watchAll=false